### ISSUE TITLE
Sudoku Board disappears if you click "Start Solving" on a solved board and doesn't return unless you refresh

### ISSUE THREAD

**Issue by Samathingamajig** [reddragonnm/sudoku-solver#1]
Title says it all.

See video below.

https://user-images.githubusercontent.com/29130894/104139974-776ee480-5374-11eb-8149-d6ba019af4ac.mp4

**Comment by Samathingamajig** [comment]
![image](https://user-images.githubusercontent.com/29130894/104140040-f49a5980-5374-11eb-9abe-65a45a0cf7b3.png)

**Comment by reddragonnm** [comment]
Thanks for creating this issue 😊
